# TODO: Define the Docker environment for this task.
# For simple tasks, this is enough:
FROM python:3.11-slim
WORKDIR /app

# For tasks with pre-existing code, COPY files into the image:
# COPY app/ /app/
